### ISSUE TITLE
Use Combine operators like `sink`?

### ISSUE THREAD

**Issue by aheze** [jiachenyee/Forever#1]
Nice library! Does it support operators like `sink` for listening to changes?

```swift
@Forever("counter") var counter = 1
var cancellables = Set<AnyCancellable>()

override func viewDidLoad() {
    super.viewDidLoad()

    $counter.sink { value in
        print("Counter: \(value)")
    }
    .store(in: &cancellables)
}
```

**Comment by jiachenyee** [comment]
I've just added support for using Combine operators 

https://github.com/jiachenyee/Forever/blob/main/README.md#using-uikit-forevercombine

**Comment by aheze** [comment]
Woah nice, thanks for your work!
